<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace GPBMetadata;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4b0a0c636f6d6d6f6e2e70726f746f120b677270632e636f6d6d6f6e22260a054572726f72120c0a04636f6465180120012803120f0a076d657373616765180220012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

