<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace GPBMetadata;

class Event
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a86020a0b6576656e742e70726f746f120a677270632e6576656e7422480a0f44697370617463685265717565737412260a046261736518012001280b32182e677270632e636f6d6d6f6e2e4261736552657175657374120d0a05706172616d18022001280922450a104469737061746368526573706f6e736512210a056572726f7218012001280b32122e677270632e636f6d6d6f6e2e4572726f72120e0a066d73675f696418022003280932520a0748616e646c657212470a086469737061746368121b2e677270632e6576656e742e4469737061746368526571756573741a1c2e677270632e6576656e742e4469737061746368526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

