<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: merchant.proto

namespace GPBMetadata;

class Merchant
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae2010a0e6d65726368616e742e70726f746f1209677270632e7573657222210a10517565727942696e6452657175657374120d0a0570686f6e6518012001280922440a11517565727942696e64526573706f6e736512210a056572726f7218012001280b32122e677270632e636f6d6d6f6e2e4572726f72120c0a046461746118022001280932540a084d65726368616e7412480a09717565727942696e64121b2e677270632e757365722e517565727942696e64526571756573741a1c2e677270632e757365722e517565727942696e64526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

