<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rule.proto

namespace GPBMetadata;

class Rule
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa0020a0a72756c652e70726f746f120b677270632e636f6e666967223c0a0a52756c6544657461696c120d0a0569735f6f6e18012001280512100a086576656e745f6964180220012805120d0a0576616c756518032001280922700a1252756c6544657461696c526573706f6e736512210a056572726f7218012001280b32122e677270632e636f6d6d6f6e2e4572726f7212270a0664657461696c18022001280b32172e677270632e636f6e6669672e52756c6544657461696c120e0a066d73675f6964180320012809324d0a0452756c6512450a0664657461696c12182e677270632e636f6d6d6f6e2e42617365526571756573741a1f2e677270632e636f6e6669672e52756c6544657461696c526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

