<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rule.proto

namespace Grpc\Config;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.config.RuleDetail</code>
 */
class RuleDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 is_on = 1;</code>
     */
    protected $is_on = 0;
    /**
     * Generated from protobuf field <code>int32 event_id = 2;</code>
     */
    protected $event_id = 0;
    /**
     * Generated from protobuf field <code>string value = 3;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $is_on
     *     @type int $event_id
     *     @type string $value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rule::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 is_on = 1;</code>
     * @return int
     */
    public function getIsOn()
    {
        return $this->is_on;
    }

    /**
     * Generated from protobuf field <code>int32 is_on = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setIsOn($var)
    {
        GPBUtil::checkInt32($var);
        $this->is_on = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 event_id = 2;</code>
     * @return int
     */
    public function getEventId()
    {
        return $this->event_id;
    }

    /**
     * Generated from protobuf field <code>int32 event_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setEventId($var)
    {
        GPBUtil::checkInt32($var);
        $this->event_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value = 3;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

