<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rule.proto

namespace Grpc\Config;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.config.RuleSaveRequest</code>
 */
class RuleSaveRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.grpc.common.BaseRequest base = 1;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>.grpc.config.RuleDetail detail = 2;</code>
     */
    protected $detail = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Grpc\Common\BaseRequest $base
     *     @type \Grpc\Config\RuleDetail $detail
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rule::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.grpc.common.BaseRequest base = 1;</code>
     * @return \Grpc\Common\BaseRequest
     */
    public function getBase()
    {
        return isset($this->base) ? $this->base : null;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.grpc.common.BaseRequest base = 1;</code>
     * @param \Grpc\Common\BaseRequest $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Common\BaseRequest::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.grpc.config.RuleDetail detail = 2;</code>
     * @return \Grpc\Config\RuleDetail
     */
    public function getDetail()
    {
        return isset($this->detail) ? $this->detail : null;
    }

    public function hasDetail()
    {
        return isset($this->detail);
    }

    public function clearDetail()
    {
        unset($this->detail);
    }

    /**
     * Generated from protobuf field <code>.grpc.config.RuleDetail detail = 2;</code>
     * @param \Grpc\Config\RuleDetail $var
     * @return $this
     */
    public function setDetail($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Config\RuleDetail::class);
        $this->detail = $var;

        return $this;
    }

}

